services:
    nuva-no-web:
        network_mode: host
        container_name: nuva-no-web
        build:
            context: .
            dockerfile: Dockerfile.local
        ports:
            - "3000:3000"
        volumes:
            - ../:/app
        tty: true

    nuva-no-cms:
        image: ghost:5-alpine
        restart: always
        network_mode: host
        container_name: nuva-no-cms
        environment:
            # see https://ghost.org/docs/config/#configuration-options
            database__client: mysql
            database__connection__host: localhost
            database__connection__user: root
            database__connection__password: password
            database__connection__database: nuva_no_cms
            # this url value is just an example, and is likely wrong for your environment!
            url: http://localhost:2368
            # contrary to the default mentioned in the linked documentation, this image defaults to NODE_ENV=production (so development mode needs to be explicitly specified if desired)
            #NODE_ENV: development
        volumes:
            - ghost:/var/lib/ghost/content

volumes:
  ghost:
